fix: make commit message commitizen compliant

diff --git a/mise-tasks/bump-version b/mise-tasks/bump-version
--- a/mise-tasks/bump-version
+++ b/mise-tasks/bump-version
@@ -60,7 +60,7 @@ env \
 if ! git diff --quiet -- global.gd; then
     printf "Updated version in %s to %s\n" "global.gd" "${new_ver}"
     git add -- global.gd || die "Failed to stage version bump."
-    git commit -m "Bump version to ${new_ver}" || die "Failed to commit version bump."
+    git commit -m "chore: bump version to ${new_ver}" || die "Failed to commit version bump."
     is_new_version=1
 fi
 
